import "./globals.css";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-montserrat">
        <div className="overflow-x-hidden"> 
          {children}
        </div>
      </body>
    </html>
  );
}
